//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonToDatabase.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonToDatabase.Common.Resources.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://robo-tst.optum.com/odata/QueueItems?$filter=QueueDefinitionId%20eq%20.
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_ErrorLogging.
        /// </summary>
        public static string ErrorLoggingProcName {
            get {
                return ResourceManager.GetString("ErrorLoggingProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_HRMS_Recollection_Report_Insert_Insert.
        /// </summary>
        public static string InserDataProcName {
            get {
                return ResourceManager.GetString("InserDataProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;Hi Team,&lt;br/&gt;&lt;br/&gt;The HRMS queue API process has been completed&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;Regards&lt;br/&gt;HDP Assistant Admin&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string Mail_Body {
            get {
                return ResourceManager.GetString("Mail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recollectionportal@optum.com.
        /// </summary>
        public static string Mail_From {
            get {
                return ResourceManager.GetString("Mail_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailo2.uhc.com.
        /// </summary>
        public static string Mail_Host {
            get {
                return ResourceManager.GetString("Mail_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string Mail_Port {
            get {
                return ResourceManager.GetString("Mail_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRMS_QueueReports.
        /// </summary>
        public static string Mail_Subject {
            get {
                return ResourceManager.GetString("Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sachin_kumar4@optum.com,pushpesh_suman@optum.com.
        /// </summary>
        public static string Mail_To {
            get {
                return ResourceManager.GetString("Mail_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lKCxacsZXS5KdOl/2qq5bQ==.
        /// </summary>
        public static string NUID {
            get {
                return ResourceManager.GetString("NUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30MzE5addo9SUApmNKAOBw==.
        /// </summary>
        public static string NUID_Password {
            get {
                return ResourceManager.GetString("NUID_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecollectionAPIToDatabase.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usp_HRMS_GetQueueID.
        /// </summary>
        public static string queueProcName {
            get {
                return ResourceManager.GetString("queueProcName", resourceCulture);
            }
        }
    }
}
